appcookieName = "mes3"
httpport = 9000
runmode = "dev"
accesslogs = true

[prod]
[prod.grace]
# 优雅关闭
driver = "signal"
stop = "INT,TERM"
start = "HUP"

# 登陆态
[prod.session]
#driver = "redisphp"
#cookieName = "ci_sessions"
#gclifetime = 2592000
#cookieLifeTime = 2592000
#providerConfig = "redis:6379,100,1"
#secure = false
#domain = "127.0.0.1"
#sessionIdLength = 20
#enableSetCookie = true

# 数据库
[prod.mdb]
#port = 27017
#host = "10.20.5.105"
#user = "admin"
#password = "password"
#database = "database"

#日志
[prod.log]
driver = "console"
prettyprint = true


#队列
[prod.queue]
driver = "memory"
poolsize = 1

#缓存
[prod.cache]
driver = "memory"
saveprefix = "cache:"

# 安全
#securityipwhite = "10.251.41.35,10.129.1.23,10.30.162.167"


[dev]
[dev.grace]
# 优雅关闭
driver = "signal"
stop = "INT,TERM"
start = "HUP"

# 登陆态
[dev.session]
#driver = "memory"
#cookieName = "ci_sessions"
#gclifetime = 2592000
#cookieLifeTime = 2592000
#providerConfig = "127.0.0.1:6379,100,1"
#secure = false
#domain = "127.0.0.1"
#sessionIdLength = 20
#enableSetCookie = true

[dev.db]
driver = "mysql"
port = 3306
host = "10.20.5.104"
user = "root"
password = "root"
database = "bakeweb"
charset = "utf8mb4"
collation = "utf8mb4_general_ci"
debug = false

[dev.mdb]
#port = 27017
#host = "10.20.5.104"
#user = "admin"
#password = "password"
#database = "database"

[dev.log]
driver = "console"
prettyprint = true

[dev.queue]
driver = "memory"
poolsize = 1

[dev.cache]
driver = "memory"
saveprefix = "cache:"

[test]
sessiondriver = "memory"
enableSetCookie = true

[test.log]
driver = "console"
level = "debug"
prettyprint = true

[test.queue]
driver = "memory"
poolsize = 1

[test.cache]
driver = "memory"
saveprefix = "cache:"


